#!/bin/bash
# POST-INSTALL CONFIGURATION GUIDE
# Run after 01_install_elastic.sh completes
# Follow these steps inside Kibana via browser at http://<ubuntu-ip>:5601

echo "Complete these steps in Kibana and Terminal after initial install."
echo ""
echo "STEP 1: Set encryption keys (required for Security rules)"
echo "  /usr/share/kibana/bin/kibana-encryption-keys generate"
echo "  Add all three keys to /etc/kibana/kibana.yml"
echo "  sudo systemctl restart kibana"
echo ""
echo "STEP 2: Configure Fleet Server"
echo "  Kibana -> Management -> Fleet -> Add Fleet Server"
echo "  Name: fleet-server-1"
echo "  URL: https://<ubuntu-ip>:8220"
echo "  Download ARM64 elastic-agent and run install command"
echo ""
echo "STEP 3: Create Agent Policy"
echo "  Fleet -> Agent Policies -> Create Agent Policy"
echo "  Name: Windows Endpoint Policy"
echo ""
echo "STEP 4: Enroll Windows Agent"
echo "  Fleet -> Add Agent -> Select Windows Endpoint Policy"
echo "  On Windows VM, download elastic-agent-x.x.x-windows-x86_64.zip"
echo "  Run: .\elastic-agent.exe install --url=https://<ubuntu-ip>:8220 --enrollment-token=<TOKEN> --insecure"
echo ""
echo "STEP 5: Verify logs flowing"
echo "  Kibana -> Discover -> logs-* index"
echo "  Filter: agent.name: <windows-hostname>"
